[package]
name = "zorg-query"
description = "SWOG LIST query boundary for Zorg."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
zorg-core = { path = "../zorg-core" }
zorg-store = { path = "../zorg-store" }

[lints]
workspace = true
