[package]
name = "zorg-store"
description = "Storage and indexing boundary for Zorg."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
rusqlite = "0.37.0"
zorg-core = { path = "../zorg-core" }
zorg-parse = { path = "../zorg-parse" }

[lints]
workspace = true
