//! Parser boundary for Zorg `.z` syntax.

use std::fmt;
use std::path::PathBuf;

use tree_sitter::{Language, Node, Parser, Point, Tree};
use tree_sitter_language::LanguageFn;
use zorg_core::{Diagnostic, SourcePath, SourcePosition, SourceSpan, ZorgError, ZorgResult};

/// Public Tree-sitter node names consumed by Zorg parser lowering.
pub mod node_kind {
    /// Root node for a parsed `.z` file.
    pub const SOURCE_FILE: &str = "source_file";
    /// Percent-fenced file or directory zettel header.
    pub const FILE_HEADER: &str = "file_header";
    /// Opening header fence line.
    pub const FILE_HEADER_OPEN: &str = "file_header_open";
    /// Closing header fence line.
    pub const FILE_HEADER_CLOSE: &str = "file_header_close";
    /// Nested zettel block.
    pub const ZETTEL_ITEM: &str = "zettel_item";
    /// First line of a nested zettel.
    pub const ZETTEL_OPENING: &str = "zettel_opening";
    /// Contiguous prose block.
    pub const PARAGRAPH: &str = "paragraph";
    /// One prose line inside a paragraph.
    pub const PARAGRAPH_LINE: &str = "paragraph_line";
    /// Markdown fenced code block.
    pub const FENCED_CODE_BLOCK: &str = "fenced_code_block";
    /// Opening code fence.
    pub const FENCE_START: &str = "fence_start";
    /// Raw code fence body.
    pub const CODE_FENCE_BODY: &str = "code_fence_body";
    /// Closing code fence.
    pub const FENCE_END: &str = "fence_end";
    /// Absolute zettel ID declaration.
    pub const ID: &str = "id";
    /// Local zettel ID declaration.
    pub const LOCAL_ID: &str = "local_id";
    /// Absolute hash link in prose.
    pub const ABSOLUTE_LINK: &str = "absolute_link";
    /// Child-relative link.
    pub const CHILD_LINK: &str = "child_link";
    /// Sibling-relative link.
    pub const SIBLING_LINK: &str = "sibling_link";
    /// Non-type tag.
    pub const TAG: &str = "tag";
    /// `#z/...` type tag.
    pub const TYPE_TAG: &str = "type_tag";
    /// Complete `key::value` property.
    pub const PROPERTY: &str = "property";
    /// Key portion of a property.
    pub const PROPERTY_KEY: &str = "property_key";
    /// Raw value portion of a property.
    pub const PROPERTY_VALUE: &str = "property_value";
    /// Todo marker token.
    pub const TODO_MARKER: &str = "todo_marker";
    /// Plain title/header/body text token.
    pub const TITLE_TEXT: &str = "title_text";
}

unsafe extern "C" {
    fn tree_sitter_zorg() -> *const ();
}

/// Returns the locally linked Zorg Tree-sitter language.
#[must_use]
pub fn zorg_language() -> Language {
    // SAFETY: `tree_sitter_zorg` is generated by the Tree-sitter CLI and linked
    // by this crate's build script from `../zorg-treesitter/src/parser.c`.
    Language::new(unsafe { LanguageFn::from_raw(tree_sitter_zorg) })
}

/// Zero-based Tree-sitter point retained for syntax-boundary consumers.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub struct SyntaxPoint {
    /// Zero-based row.
    pub row: usize,
    /// Zero-based byte column.
    pub column: usize,
}

impl From<Point> for SyntaxPoint {
    fn from(point: Point) -> Self {
        Self {
            row: point.row,
            column: point.column,
        }
    }
}

/// Source range for a syntax node.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub struct SyntaxRange {
    /// Start byte offset, inclusive.
    pub start_byte: usize,
    /// End byte offset, exclusive.
    pub end_byte: usize,
    /// Zero-based Tree-sitter start point.
    pub start_point: SyntaxPoint,
    /// Zero-based Tree-sitter end point.
    pub end_point: SyntaxPoint,
}

impl SyntaxRange {
    fn from_node(node: Node<'_>) -> Self {
        Self {
            start_byte: node.start_byte(),
            end_byte: node.end_byte(),
            start_point: node.start_position().into(),
            end_point: node.end_position().into(),
        }
    }

    fn to_source_span(self) -> SourceSpan {
        SourceSpan::positioned(
            SourcePosition::new(
                self.start_byte,
                self.start_point.row + 1,
                self.start_point.column + 1,
            ),
            SourcePosition::new(
                self.end_byte,
                self.end_point.row + 1,
                self.end_point.column + 1,
            ),
        )
    }
}

/// Stable metadata for a syntax node without exposing Tree-sitter lifetimes.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct SyntaxNodeMetadata {
    /// Public or internal Tree-sitter node kind.
    pub kind: &'static str,
    /// Source range for this node.
    pub range: SyntaxRange,
    /// Total child count.
    pub child_count: usize,
    /// Named child count.
    pub named_child_count: usize,
    /// True when this node or a descendant contains an error.
    pub has_error: bool,
    /// True when this node is an `ERROR` recovery node.
    pub is_error: bool,
    /// True when Tree-sitter inserted this missing node during recovery.
    pub is_missing: bool,
}

impl SyntaxNodeMetadata {
    fn from_node(node: Node<'_>) -> Self {
        Self {
            kind: node.kind(),
            range: SyntaxRange::from_node(node),
            child_count: node.child_count(),
            named_child_count: node.named_child_count(),
            has_error: node.has_error(),
            is_error: node.is_error(),
            is_missing: node.is_missing(),
        }
    }
}

/// Parsed `.z` source plus the retained Tree-sitter tree.
pub struct ParsedSyntaxDocument {
    /// Original UTF-8 source text.
    pub source: String,
    /// Source file path when provided.
    pub path: Option<SourcePath>,
    /// Retained Tree-sitter tree for later traversal/lowering.
    pub tree: Tree,
    /// Root node metadata without Tree-sitter lifetimes.
    pub root: SyntaxNodeMetadata,
    /// Syntax diagnostics from Tree-sitter recovery and required-boundary checks.
    pub diagnostics: Vec<Diagnostic>,
}

impl ParsedSyntaxDocument {
    /// Returns the live Tree-sitter root node.
    #[must_use]
    pub fn root_node(&self) -> Node<'_> {
        self.tree.root_node()
    }

    /// Returns the root S-expression for tests, debugging, and golden snapshots.
    #[must_use]
    pub fn root_sexp(&self) -> String {
        self.root_node().to_sexp()
    }
}

impl fmt::Debug for ParsedSyntaxDocument {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ParsedSyntaxDocument")
            .field("source", &self.source)
            .field("path", &self.path)
            .field("root", &self.root)
            .field("diagnostics", &self.diagnostics)
            .finish_non_exhaustive()
    }
}

/// Backward-compatible name for the parser-boundary document.
pub type ParsedDocument = ParsedSyntaxDocument;

/// Parses a `.z` source document into a real Tree-sitter syntax tree.
pub fn parse_document(source: &str) -> ZorgResult<ParsedDocument> {
    parse_syntax(source)
}

/// Parses a `.z` source document into a real Tree-sitter syntax tree.
pub fn parse_syntax(source: &str) -> ZorgResult<ParsedSyntaxDocument> {
    parse_syntax_inner(source, None)
}

/// Parses a `.z` source document and records its source path.
pub fn parse_syntax_with_path(
    source: &str,
    path: impl Into<PathBuf>,
) -> ZorgResult<ParsedSyntaxDocument> {
    parse_syntax_inner(source, Some(SourcePath::new(path.into())))
}

fn parse_syntax_inner(source: &str, path: Option<SourcePath>) -> ZorgResult<ParsedSyntaxDocument> {
    let language = zorg_language();
    let mut parser = Parser::new();
    parser.set_language(&language).map_err(|_| {
        ZorgError::Unsupported("zorg Tree-sitter grammar ABI is incompatible with this parser")
    })?;

    let tree = parser.parse(source, None).ok_or(ZorgError::Unsupported(
        "zorg Tree-sitter parser did not produce a syntax tree",
    ))?;
    let root_node = tree.root_node();
    let root = SyntaxNodeMetadata::from_node(root_node);
    let mut diagnostics = Vec::new();

    if root.kind != node_kind::SOURCE_FILE {
        diagnostics.push(with_optional_path(
            Diagnostic::syntax_recovery(
                format!("expected root node `{}`", node_kind::SOURCE_FILE),
                Some(root.range.to_source_span()),
            ),
            path.as_ref(),
        ));
    }

    if !has_descendant_kind(root_node, node_kind::FILE_HEADER) {
        diagnostics.push(with_optional_path(
            Diagnostic::syntax_recovery(
                "missing required file header",
                Some(root.range.to_source_span()),
            ),
            path.as_ref(),
        ));
    }

    collect_recovery_diagnostics(root_node, path.as_ref(), &mut diagnostics);

    Ok(ParsedSyntaxDocument {
        source: source.to_owned(),
        path,
        tree,
        root,
        diagnostics,
    })
}

fn collect_recovery_diagnostics(
    node: Node<'_>,
    path: Option<&SourcePath>,
    diagnostics: &mut Vec<Diagnostic>,
) {
    if node.is_error() {
        diagnostics.push(with_optional_path(
            Diagnostic::syntax_recovery(
                "Tree-sitter recovered an ERROR node",
                Some(SyntaxRange::from_node(node).to_source_span()),
            ),
            path,
        ));
    }

    if node.is_missing() {
        diagnostics.push(with_optional_path(
            Diagnostic::syntax_recovery(
                format!("Tree-sitter inserted missing `{}`", node.kind()),
                Some(SyntaxRange::from_node(node).to_source_span()),
            ),
            path,
        ));
    }

    for index in 0..node.child_count() {
        if let Some(child) = node.child(index.try_into().expect("node child index fits in u32")) {
            collect_recovery_diagnostics(child, path, diagnostics);
        }
    }
}

fn has_descendant_kind(node: Node<'_>, kind: &str) -> bool {
    if node.kind() == kind {
        return true;
    }

    for index in 0..node.child_count() {
        let Some(child) = node.child(index.try_into().expect("node child index fits in u32"))
        else {
            continue;
        };

        if has_descendant_kind(child, kind) {
            return true;
        }
    }

    false
}

fn with_optional_path(mut diagnostic: Diagnostic, path: Option<&SourcePath>) -> Diagnostic {
    if let Some(path) = path {
        diagnostic.path = Some(path.clone());
    }

    diagnostic
}

#[cfg(test)]
mod tests {
    use super::{node_kind, parse_document, parse_syntax_with_path, zorg_language};
    use std::fs;
    use std::path::{Path, PathBuf};
    use tree_sitter::Node;

    const VALID_FIXTURES: &[&str] = &[
        "minimal.z",
        "nested.z",
        "query_and_template.z",
        "dir/init.z",
    ];

    const PUBLIC_NODE_KINDS: &[&str] = &[
        node_kind::SOURCE_FILE,
        node_kind::FILE_HEADER,
        node_kind::FILE_HEADER_OPEN,
        node_kind::FILE_HEADER_CLOSE,
        node_kind::ZETTEL_ITEM,
        node_kind::ZETTEL_OPENING,
        node_kind::PARAGRAPH,
        node_kind::PARAGRAPH_LINE,
        node_kind::FENCED_CODE_BLOCK,
        node_kind::FENCE_START,
        node_kind::CODE_FENCE_BODY,
        node_kind::FENCE_END,
        node_kind::ID,
        node_kind::LOCAL_ID,
        node_kind::ABSOLUTE_LINK,
        node_kind::CHILD_LINK,
        node_kind::SIBLING_LINK,
        node_kind::TAG,
        node_kind::TYPE_TAG,
        node_kind::PROPERTY,
        node_kind::PROPERTY_KEY,
        node_kind::PROPERTY_VALUE,
        node_kind::TODO_MARKER,
        node_kind::TITLE_TEXT,
    ];

    #[test]
    fn exposes_expected_public_node_kinds() {
        let language = zorg_language();

        for kind in PUBLIC_NODE_KINDS {
            assert_ne!(
                language.id_for_node_kind(kind, true),
                0,
                "missing public node kind `{kind}`"
            );
        }
    }

    #[test]
    fn parse_document_routes_to_tree_sitter_boundary() {
        let source = fs::read_to_string(fixture_path("minimal.z")).expect("fixture");
        let document = parse_document(&source).expect("parse");

        assert_eq!(document.root.kind, node_kind::SOURCE_FILE);
        assert!(!document.root.has_error);
        assert!(document.diagnostics.is_empty());
        assert!(document.root_sexp().contains(node_kind::FILE_HEADER));
    }

    #[test]
    fn parses_valid_corpus_without_recovery_errors() {
        for fixture in VALID_FIXTURES {
            let path = fixture_path(fixture);
            let source = fs::read_to_string(&path).expect("fixture");
            let document = parse_syntax_with_path(&source, path.clone()).expect("parse");

            assert_eq!(
                document.root.kind,
                node_kind::SOURCE_FILE,
                "wrong root for {}",
                path.display()
            );
            assert!(
                !document.root.has_error,
                "Tree-sitter reported errors for {}:\n{}",
                path.display(),
                document.root_sexp()
            );
            assert!(
                document.diagnostics.is_empty(),
                "unexpected diagnostics for {}: {:#?}",
                path.display(),
                document.diagnostics
            );
            assert_eq!(
                document.path.as_ref().expect("path").as_path(),
                path.as_path()
            );
        }
    }

    #[test]
    fn parses_legacy_invalid_as_source_without_compatibility_nodes() {
        let path = fixture_path("legacy_invalid.z");
        let source = fs::read_to_string(&path).expect("fixture");
        let document = parse_syntax_with_path(&source, path).expect("parse");
        let root = document.root_node();

        assert!(!document.root.has_error);
        assert!(document.diagnostics.is_empty());
        assert_eq!(count_kind(root, node_kind::ID), 1);
        assert_eq!(count_kind(root, node_kind::LOCAL_ID), 0);
        assert_eq!(count_kind(root, node_kind::PROPERTY), 0);
        assert_eq!(count_kind(root, node_kind::FENCED_CODE_BLOCK), 0);
    }

    #[test]
    fn reports_missing_file_header_as_syntax_diagnostic() {
        let document = parse_document("Body only\n").expect("parse");

        assert_eq!(document.root.kind, node_kind::SOURCE_FILE);
        assert_eq!(document.diagnostics.len(), 1);
        assert_eq!(
            document.diagnostics[0].code.as_deref(),
            Some("syntax.recovery")
        );
        assert!(
            document.diagnostics[0]
                .message
                .contains("missing required file header")
        );
    }

    fn fixture_path(path: impl AsRef<Path>) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .join("fixtures/corpus")
            .join(path)
    }

    fn count_kind(node: Node<'_>, kind: &str) -> usize {
        let mut count = usize::from(node.kind() == kind);

        for index in 0..node.child_count() {
            if let Some(child) = node.child(index.try_into().expect("node child index fits in u32"))
            {
                count += count_kind(child, kind);
            }
        }

        count
    }
}
